                                                                                
  GRANT ALTER SYSTEM TO "SCOTT"                                                 
  GRANT AUDIT SYSTEM TO "SCOTT"                                                 
  GRANT CREATE SESSION TO "SCOTT"                                               
  GRANT ALTER SESSION TO "SCOTT"                                                
  GRANT RESTRICTED SESSION TO "SCOTT"                                           
  GRANT CREATE TABLESPACE TO "SCOTT"                                            
  GRANT ALTER TABLESPACE TO "SCOTT"                                             
  GRANT MANAGE TABLESPACE TO "SCOTT"                                            
  GRANT DROP TABLESPACE TO "SCOTT"                                              
  GRANT UNLIMITED TABLESPACE TO "SCOTT"                                         
  GRANT CREATE USER TO "SCOTT"                                                  
  GRANT BECOME USER TO "SCOTT"                                                  
  GRANT ALTER USER TO "SCOTT"                                                   
  GRANT DROP USER TO "SCOTT"                                                    
  GRANT CREATE ROLLBACK SEGMENT TO "SCOTT"                                      
  GRANT ALTER ROLLBACK SEGMENT TO "SCOTT"                                       
  GRANT DROP ROLLBACK SEGMENT TO "SCOTT"                                        
  GRANT CREATE TABLE TO "SCOTT"                                                 
  GRANT CREATE ANY TABLE TO "SCOTT"                                             
  GRANT ALTER ANY TABLE TO "SCOTT"                                              
  GRANT BACKUP ANY TABLE TO "SCOTT"                                             
  GRANT DROP ANY TABLE TO "SCOTT"                                               
  GRANT LOCK ANY TABLE TO "SCOTT"                                               
  GRANT COMMENT ANY TABLE TO "SCOTT"                                            
  GRANT SELECT ANY TABLE TO "SCOTT"                                             
  GRANT INSERT ANY TABLE TO "SCOTT"                                             
  GRANT UPDATE ANY TABLE TO "SCOTT"                                             
  GRANT DELETE ANY TABLE TO "SCOTT"                                             
  GRANT REDEFINE ANY TABLE TO "SCOTT"                                           
  GRANT CREATE CLUSTER TO "SCOTT"                                               
  GRANT CREATE ANY CLUSTER TO "SCOTT"                                           
  GRANT ALTER ANY CLUSTER TO "SCOTT"                                            
  GRANT DROP ANY CLUSTER TO "SCOTT"                                             
  GRANT CREATE ANY INDEX TO "SCOTT"                                             
  GRANT ALTER ANY INDEX TO "SCOTT"                                              
  GRANT DROP ANY INDEX TO "SCOTT"                                               
  GRANT CREATE SYNONYM TO "SCOTT"                                               
  GRANT CREATE ANY SYNONYM TO "SCOTT"                                           
  GRANT DROP ANY SYNONYM TO "SCOTT"                                             
  GRANT CREATE PUBLIC SYNONYM TO "SCOTT"                                        
  GRANT DROP PUBLIC SYNONYM TO "SCOTT"                                          
  GRANT CREATE VIEW TO "SCOTT"                                                  
  GRANT CREATE ANY VIEW TO "SCOTT"                                              
  GRANT DROP ANY VIEW TO "SCOTT"                                                
  GRANT CREATE SEQUENCE TO "SCOTT"                                              
  GRANT CREATE ANY SEQUENCE TO "SCOTT"                                          
  GRANT ALTER ANY SEQUENCE TO "SCOTT"                                           
  GRANT DROP ANY SEQUENCE TO "SCOTT"                                            
  GRANT SELECT ANY SEQUENCE TO "SCOTT"                                          
  GRANT CREATE DATABASE LINK TO "SCOTT"                                         
  GRANT CREATE PUBLIC DATABASE LINK TO "SCOTT"                                  
  GRANT DROP PUBLIC DATABASE LINK TO "SCOTT"                                    
  GRANT CREATE ROLE TO "SCOTT"                                                  
  GRANT DROP ANY ROLE TO "SCOTT"                                                
  GRANT GRANT ANY ROLE TO "SCOTT"                                               
  GRANT ALTER ANY ROLE TO "SCOTT"                                               
  GRANT AUDIT ANY TO "SCOTT"                                                    
  GRANT ALTER DATABASE TO "SCOTT"                                               
  GRANT FORCE TRANSACTION TO "SCOTT"                                            
  GRANT FORCE ANY TRANSACTION TO "SCOTT"                                        
  GRANT CREATE PROCEDURE TO "SCOTT"                                             
  GRANT CREATE ANY PROCEDURE TO "SCOTT"                                         
  GRANT ALTER ANY PROCEDURE TO "SCOTT"                                          
  GRANT DROP ANY PROCEDURE TO "SCOTT"                                           
  GRANT EXECUTE ANY PROCEDURE TO "SCOTT"                                        
  GRANT CREATE TRIGGER TO "SCOTT"                                               
  GRANT CREATE ANY TRIGGER TO "SCOTT"                                           
  GRANT ALTER ANY TRIGGER TO "SCOTT"                                            
  GRANT DROP ANY TRIGGER TO "SCOTT"                                             
  GRANT CREATE PROFILE TO "SCOTT"                                               
  GRANT ALTER PROFILE TO "SCOTT"                                                
  GRANT DROP PROFILE TO "SCOTT"                                                 
  GRANT ALTER RESOURCE COST TO "SCOTT"                                          
  GRANT ANALYZE ANY TO "SCOTT"                                                  
  GRANT GRANT ANY PRIVILEGE TO "SCOTT"                                          
  GRANT CREATE MATERIALIZED VIEW TO "SCOTT"                                     
  GRANT CREATE ANY MATERIALIZED VIEW TO "SCOTT"                                 
  GRANT ALTER ANY MATERIALIZED VIEW TO "SCOTT"                                  
  GRANT DROP ANY MATERIALIZED VIEW TO "SCOTT"                                   
  GRANT CREATE ANY DIRECTORY TO "SCOTT"                                         
  GRANT DROP ANY DIRECTORY TO "SCOTT"                                           
  GRANT CREATE TYPE TO "SCOTT"                                                  
  GRANT CREATE ANY TYPE TO "SCOTT"                                              
  GRANT ALTER ANY TYPE TO "SCOTT"                                               
  GRANT DROP ANY TYPE TO "SCOTT"                                                
  GRANT EXECUTE ANY TYPE TO "SCOTT"                                             
  GRANT UNDER ANY TYPE TO "SCOTT"                                               
  GRANT CREATE LIBRARY TO "SCOTT"                                               
  GRANT CREATE ANY LIBRARY TO "SCOTT"                                           
  GRANT ALTER ANY LIBRARY TO "SCOTT"                                            
  GRANT DROP ANY LIBRARY TO "SCOTT"                                             
  GRANT EXECUTE ANY LIBRARY TO "SCOTT"                                          
  GRANT CREATE OPERATOR TO "SCOTT"                                              
  GRANT CREATE ANY OPERATOR TO "SCOTT"                                          
  GRANT ALTER ANY OPERATOR TO "SCOTT"                                           
  GRANT DROP ANY OPERATOR TO "SCOTT"                                            
  GRANT EXECUTE ANY OPERATOR TO "SCOTT"                                         
  GRANT CREATE INDEXTYPE TO "SCOTT"                                             
  GRANT CREATE ANY INDEXTYPE TO "SCOTT"                                         
  GRANT ALTER ANY INDEXTYPE TO "SCOTT"                                          
  GRANT DROP ANY INDEXTYPE TO "SCOTT"                                           
  GRANT UNDER ANY VIEW TO "SCOTT"                                               
  GRANT QUERY REWRITE TO "SCOTT"                                                
  GRANT GLOBAL QUERY REWRITE TO "SCOTT"                                         
  GRANT EXECUTE ANY INDEXTYPE TO "SCOTT"                                        
  GRANT UNDER ANY TABLE TO "SCOTT"                                              
  GRANT CREATE DIMENSION TO "SCOTT"                                             
  GRANT CREATE ANY DIMENSION TO "SCOTT"                                         
  GRANT ALTER ANY DIMENSION TO "SCOTT"                                          
  GRANT DROP ANY DIMENSION TO "SCOTT"                                           
  GRANT CREATE ANY CONTEXT TO "SCOTT"                                           
  GRANT DROP ANY CONTEXT TO "SCOTT"                                             
  GRANT CREATE ANY OUTLINE TO "SCOTT"                                           
  GRANT ALTER ANY OUTLINE TO "SCOTT"                                            
  GRANT DROP ANY OUTLINE TO "SCOTT"                                             
  GRANT ADMINISTER DATABASE TRIGGER TO "SCOTT"                                  
  GRANT MERGE ANY VIEW TO "SCOTT"                                               
  GRANT ON COMMIT REFRESH TO "SCOTT"                                            
  GRANT EXEMPT ACCESS POLICY TO "SCOTT"                                         
  GRANT RESUMABLE TO "SCOTT"                                                    
  GRANT SELECT ANY DICTIONARY TO "SCOTT"                                        
  GRANT DEBUG CONNECT SESSION TO "SCOTT"                                        
  GRANT DEBUG ANY PROCEDURE TO "SCOTT"                                          
  GRANT FLASHBACK ANY TABLE TO "SCOTT"                                          
  GRANT GRANT ANY OBJECT PRIVILEGE TO "SCOTT"                                   
  GRANT EXPORT FULL DATABASE TO "SCOTT"                                         
  GRANT IMPORT FULL DATABASE TO "SCOTT"                                         
  GRANT ANALYZE ANY DICTIONARY TO "SCOTT"                                       
  GRANT ADVISOR TO "SCOTT"                                                      
  GRANT CREATE JOB TO "SCOTT"                                                   
  GRANT CREATE ANY JOB TO "SCOTT"                                               
  GRANT EXECUTE ANY PROGRAM TO "SCOTT"                                          
  GRANT EXECUTE ANY CLASS TO "SCOTT"                                            
  GRANT MANAGE SCHEDULER TO "SCOTT"                                             
  GRANT SELECT ANY TRANSACTION TO "SCOTT"                                       
  GRANT DROP ANY SQL PROFILE TO "SCOTT"                                         
  GRANT ALTER ANY SQL PROFILE TO "SCOTT"                                        
  GRANT ADMINISTER SQL TUNING SET TO "SCOTT"                                    
  GRANT ADMINISTER ANY SQL TUNING SET TO "SCOTT"                                
  GRANT CREATE ANY SQL PROFILE TO "SCOTT"                                       
  GRANT EXEMPT IDENTITY POLICY TO "SCOTT"                                       
  GRANT CHANGE NOTIFICATION TO "SCOTT"                                          
  GRANT CREATE EXTERNAL JOB TO "SCOTT"                                          
  GRANT CREATE ANY EDITION TO "SCOTT"                                           
  GRANT DROP ANY EDITION TO "SCOTT"                                             
  GRANT ALTER ANY EDITION TO "SCOTT"                                            
  GRANT CREATE ASSEMBLY TO "SCOTT"                                              
  GRANT CREATE ANY ASSEMBLY TO "SCOTT"                                          
  GRANT ALTER ANY ASSEMBLY TO "SCOTT"                                           
  GRANT DROP ANY ASSEMBLY TO "SCOTT"                                            
  GRANT EXECUTE ANY ASSEMBLY TO "SCOTT"                                         
  GRANT EXECUTE ASSEMBLY TO "SCOTT"                                             
  GRANT CREATE MINING MODEL TO "SCOTT"                                          
  GRANT CREATE ANY MINING MODEL TO "SCOTT"                                      
  GRANT DROP ANY MINING MODEL TO "SCOTT"                                        
  GRANT SELECT ANY MINING MODEL TO "SCOTT"                                      
  GRANT ALTER ANY MINING MODEL TO "SCOTT"                                       
  GRANT COMMENT ANY MINING MODEL TO "SCOTT"                                     
  GRANT CREATE CUBE DIMENSION TO "SCOTT"                                        
  GRANT ALTER ANY CUBE DIMENSION TO "SCOTT"                                     
  GRANT CREATE ANY CUBE DIMENSION TO "SCOTT"                                    
  GRANT DELETE ANY CUBE DIMENSION TO "SCOTT"                                    
  GRANT DROP ANY CUBE DIMENSION TO "SCOTT"                                      
  GRANT INSERT ANY CUBE DIMENSION TO "SCOTT"                                    
  GRANT SELECT ANY CUBE DIMENSION TO "SCOTT"                                    
  GRANT CREATE CUBE TO "SCOTT"                                                  
  GRANT ALTER ANY CUBE TO "SCOTT"                                               
  GRANT CREATE ANY CUBE TO "SCOTT"                                              
  GRANT DROP ANY CUBE TO "SCOTT"                                                
  GRANT SELECT ANY CUBE TO "SCOTT"                                              
  GRANT UPDATE ANY CUBE TO "SCOTT"                                              
  GRANT CREATE MEASURE FOLDER TO "SCOTT"                                        
  GRANT CREATE ANY MEASURE FOLDER TO "SCOTT"                                    
  GRANT DELETE ANY MEASURE FOLDER TO "SCOTT"                                    
  GRANT DROP ANY MEASURE FOLDER TO "SCOTT"                                      
  GRANT INSERT ANY MEASURE FOLDER TO "SCOTT"                                    
  GRANT CREATE CUBE BUILD PROCESS TO "SCOTT"                                    
  GRANT CREATE ANY CUBE BUILD PROCESS TO "SCOTT"                                
  GRANT DROP ANY CUBE BUILD PROCESS TO "SCOTT"                                  
  GRANT UPDATE ANY CUBE BUILD PROCESS TO "SCOTT"                                
  GRANT UPDATE ANY CUBE DIMENSION TO "SCOTT"                                    
  GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "SCOTT"                             
  GRANT ALTER PUBLIC DATABASE LINK TO "SCOTT"                                   
  GRANT ALTER DATABASE LINK TO "SCOTT"                                          
  GRANT CREATE SQL TRANSLATION PROFILE TO "SCOTT"                               
  GRANT CREATE ANY SQL TRANSLATION PROFILE TO "SCOTT"                           
  GRANT ALTER ANY SQL TRANSLATION PROFILE TO "SCOTT"                            
  GRANT USE ANY SQL TRANSLATION PROFILE TO "SCOTT"                              
  GRANT DROP ANY SQL TRANSLATION PROFILE TO "SCOTT"                             
  GRANT ADMINISTER KEY MANAGEMENT TO "SCOTT"                                    
  GRANT KEEP DATE TIME TO "SCOTT"                                               
  GRANT KEEP SYSGUID TO "SCOTT"                                                 
  GRANT EM EXPRESS CONNECT TO "SCOTT"                                           
  GRANT PURGE DBA_RECYCLEBIN TO "SCOTT"                                         
  GRANT FLASHBACK ARCHIVE ADMINISTER TO "SCOTT"                                 
  GRANT EXEMPT REDACTION POLICY TO "SCOTT"                                      
  GRANT INHERIT ANY PRIVILEGES TO "SCOTT"                                       
  GRANT TRANSLATE ANY SQL TO "SCOTT"                                            
  GRANT INHERIT ANY REMOTE PRIVILEGES TO "SCOTT"                                
  GRANT CREATE PLUGGABLE DATABASE TO "SCOTT"                                    
  GRANT SET CONTAINER TO "SCOTT"                                                
  GRANT CREATE LOCKDOWN PROFILE TO "SCOTT"                                      
  GRANT DROP LOCKDOWN PROFILE TO "SCOTT"                                        
  GRANT ALTER LOCKDOWN PROFILE TO "SCOTT"                                       
  GRANT CREATE CREDENTIAL TO "SCOTT"                                            
  GRANT CREATE ANY CREDENTIAL TO "SCOTT"                                        
  GRANT LOGMINING TO "SCOTT"                                                    
  GRANT USE ANY JOB RESOURCE TO "SCOTT"                                         
  GRANT EXEMPT DML REDACTION POLICY TO "SCOTT"                                  
  GRANT EXEMPT DDL REDACTION POLICY TO "SCOTT"                                  
  GRANT SELECT ANY MEASURE FOLDER TO "SCOTT"                                    
  GRANT ALTER ANY MEASURE FOLDER TO "SCOTT"                                     
  GRANT SELECT ANY CUBE BUILD PROCESS TO "SCOTT"                                
  GRANT ALTER ANY CUBE BUILD PROCESS TO "SCOTT"                                 
  GRANT READ ANY TABLE TO "SCOTT"                                               
  GRANT CREATE ATTRIBUTE DIMENSION TO "SCOTT"                                   
  GRANT CREATE ANY ATTRIBUTE DIMENSION TO "SCOTT"                               
  GRANT ALTER ANY ATTRIBUTE DIMENSION TO "SCOTT"                                
  GRANT DROP ANY ATTRIBUTE DIMENSION TO "SCOTT"                                 
  GRANT CREATE HIERARCHY TO "SCOTT"                                             
  GRANT CREATE ANY HIERARCHY TO "SCOTT"                                         
  GRANT ALTER ANY HIERARCHY TO "SCOTT"                                          
  GRANT DROP ANY HIERARCHY TO "SCOTT"                                           
  GRANT CREATE ANALYTIC VIEW TO "SCOTT"                                         
  GRANT CREATE ANY ANALYTIC VIEW TO "SCOTT"                                     
  GRANT ALTER ANY ANALYTIC VIEW TO "SCOTT"                                      
  GRANT DROP ANY ANALYTIC VIEW TO "SCOTT"                                       
                                                                                

